#ifndef COMMONHEAD_H
#define COMMONHEAD_H
/// c++ libs
#include <stdlib.h>
#include <iostream>
#include <string.h>
#include <fstream>
#include <stdlib.h>
#include <stdio.h>
#include <iostream>
#include <vector>
#include <utility>
#include <cassert>
#include <stdlib.h>
#include <string>
#include <sstream>

/// ROOT libs
#include <TROOT.h>
#include <TObject.h>
#include <TSelector.h>
#include <TLorentzVector.h>
#include <TClonesArray.h>
#include <TChain.h>
#include <TMath.h>
#include <TStopwatch.h>
#include <TCanvas.h>
#include <TFile.h>
#include <TH1F.h>
#include <TH2F.h>
#include <TTree.h>
#include <TString.h>
#include <TH2.h>
#include <THStack.h>
#include <TLegend.h>
#include <TPad.h>
#include <TF1.h>
#include <TDirectory.h>
#include <TStyle.h>
#include <TLine.h>
#include <TFrame.h>
#include <TAxis.h>
#include <TPaveText.h>
#include <TLatex.h>
#include <TSystem.h>
#include <TRandom.h>
#include <TApplication.h>
#include <TMVA/Tools.h>
#include <TGraph.h>
#include <TMultiGraph.h>
#include <TGraphAsymmErrors.h>
#include <TGraphErrors.h>
#endif
